POST /user HTTP/2
host: localhost:3000
content-type: application/json
###

###
GET localhost:3000/users
###
POST localhost:3000/users

{
"vorName":"jojo",
"nachName":"gg",
"email":"a@b.veee",
"passWort":"dg"
}
###
GET localhost:3000/users/a@b.cd

###
PUT localhost:3000/users/a@b.cd

{
"vorName": "tt",
"nachName": "bb",
"email": "www@email.cd"
}
