POST /user HTTP/2
host: localhost:3000
content-type: application/json

###

###
GET localhost:3000/users

###
GET localhost:3000/uernames

###
POST /users/
host:localhost:3000
Content-Type: application/json
Accept: application/json

{
  "vorName": "Kevin",
  "nachName": "Schroeder",
  "email": "kev90qgmx.de",
  "passWort": "zocken"
}

###
GET localhost:3000/users/a@b.cd

###
GET localhost:3000/users/

###
GET localhost:3000/users/jamiku@jp.co

###
POST localhost:3000/users

{
"vorName": "tt",
"nachName": "bb",
"email": "www@email.cd"
"passWort":"fegege"
}

###
DELETE localhost:3000/users/qs@eee.cefd

{
"email":"qs@eee.cefd"
}
