POST /user HTTP/2
host: localhost:3000
content-type: application/json

###
GET localhost:3000/users/jamiku@jp.co

###
GET localhost:3000/users

###
GET localhost:3000/uernames

###
POST /users/user
host:localhost:3000
Content-Type: application/json
Accept: application/json

{
  "vorName": "Kevin",
  "nachName": "Schroeder",
  "email": "kev90qgmx.de",
  "passWort": "zocken"
}

###
POST localhost:3000/users

{
"vorName": "tt",
"nachName": "bb",
"email": "www@email.cd"
"passWort":"fegege"
}

###
DELETE localhost:3000/users/user
Content-Type: application/json
Accept: application/json

{
"email":"qs@eee.cefd"
}
###
DELETE localhost:3000/users/user
Content-Type: application/json
Accept: application/json

{
"email":"Joe.schw@aol.com"
}
### not password
PUT  http://localhost:3000/users/update
host:localhost:3000
Content-Type: application/json
Accept: application/json

{
  "vorName":"joaquin",
  "nachName":"ssadsa",
  "email":"qaa@aa.cad",
  "password":"sssss"
}
### korrekt

PUT  http://localhost:3000/users/update
host:localhost:3000
Content-Type: application/json
Accept: application/json

{
  "vorName":"joaquin",
  "nachName":"ssadsa",
  "email":"Nullam@felis.co.uk"
}
